/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "OAuth.h"

bool_t
xdr_authorization (XDR *xdrs, authorization *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id, 16))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh, 2))
		 return FALSE;
	return TRUE;
}
