/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "OAuth.h"

bool_t
xdr_authorization (XDR *xdrs, authorization *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id, 16))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_approve (XDR *xdrs, approve *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->authorization_token, 16))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_approve_response (XDR *xdrs, approve_response *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->authorization_token, 16))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->verify))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->permissions, 50))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_access (XDR *xdrs, access *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id, 16))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh, 2))
		 return FALSE;
	 if (!xdr_approve_response (xdrs, &objp->authorization_token))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_access_response (XDR *xdrs, access_response *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->access_token, 16))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, 16))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->valability))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_action (XDR *xdrs, action *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->operation, 10))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->source, 15))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, 16))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_refresh_input (XDR *xdrs, refresh_input *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id, 16))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh, 16))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_refresh_output (XDR *xdrs, refresh_output *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->access_token, 16))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, 16))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->valability))
		 return FALSE;
	return TRUE;
}
