/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OAUTH_H_RPCGEN
#define _OAUTH_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct authorization {
	char *id;
};
typedef struct authorization authorization;

struct approve {
	char *authorization_token;
};
typedef struct approve approve;

struct approve_response {
	char *authorization_token;
	int verify;
	char *permissions;
};
typedef struct approve_response approve_response;

struct access {
	char *id;
	char *refresh;
	approve_response authorization_token;
};
typedef struct access access;

struct access_response {
	char *access_token;
	char *refresh_token;
	int valability;
};
typedef struct access_response access_response;

struct action {
	char *operation;
	char *source;
	char *access_token;
};
typedef struct action action;

#define GRADE_PROG 0x31234567
#define GRADE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define request_authorization_token 1
extern  char ** request_authorization_token_1(authorization *, CLIENT *);
extern  char ** request_authorization_token_1_svc(authorization *, struct svc_req *);
#define approve_request_token 2
extern  approve_response * approve_request_token_1(approve *, CLIENT *);
extern  approve_response * approve_request_token_1_svc(approve *, struct svc_req *);
#define request_access_token 3
extern  access_response * request_access_token_1(access *, CLIENT *);
extern  access_response * request_access_token_1_svc(access *, struct svc_req *);
extern int grade_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define request_authorization_token 1
extern  char ** request_authorization_token_1();
extern  char ** request_authorization_token_1_svc();
#define approve_request_token 2
extern  approve_response * approve_request_token_1();
extern  approve_response * approve_request_token_1_svc();
#define request_access_token 3
extern  access_response * request_access_token_1();
extern  access_response * request_access_token_1_svc();
extern int grade_prog_1_freeresult ();
#endif /* K&R C */
#define GRADE_VERS_2 2

#if defined(__STDC__) || defined(__cplusplus)
#define validate_delegated_action 1
extern  char ** validate_delegated_action_2(action *, CLIENT *);
extern  char ** validate_delegated_action_2_svc(action *, struct svc_req *);
extern int grade_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define validate_delegated_action 1
extern  char ** validate_delegated_action_2();
extern  char ** validate_delegated_action_2_svc();
extern int grade_prog_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_authorization (XDR *, authorization*);
extern  bool_t xdr_approve (XDR *, approve*);
extern  bool_t xdr_approve_response (XDR *, approve_response*);
extern  bool_t xdr_access (XDR *, access*);
extern  bool_t xdr_access_response (XDR *, access_response*);
extern  bool_t xdr_action (XDR *, action*);

#else /* K&R C */
extern bool_t xdr_authorization ();
extern bool_t xdr_approve ();
extern bool_t xdr_approve_response ();
extern bool_t xdr_access ();
extern bool_t xdr_access_response ();
extern bool_t xdr_action ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OAUTH_H_RPCGEN */
