/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OAUTH_H_RPCGEN
#define _OAUTH_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct authorization {
	char *id;
	char *refresh;
};
typedef struct authorization authorization;

#define GRADE_PROG 0x31234567
#define GRADE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define request_authorization_token 1
extern  char ** request_authorization_token_1(authorization *, CLIENT *);
extern  char ** request_authorization_token_1_svc(authorization *, struct svc_req *);
extern int grade_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define request_authorization_token 1
extern  char ** request_authorization_token_1();
extern  char ** request_authorization_token_1_svc();
extern int grade_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_authorization (XDR *, authorization*);

#else /* K&R C */
extern bool_t xdr_authorization ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OAUTH_H_RPCGEN */
