/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "OAuth.h"
#include "OAuth_utils.h"

void
grade_prog_1(char *host, char *path)
{
	CLIENT *clnt;
	char * *result_1;
	authorization  request_authorization_token_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, GRADE_PROG, GRADE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	int size_orders = 0;
	ClientOrder* orders = get_orders(path, &size_orders);
	request_authorization_token_1_arg.id = calloc(16, sizeof(char));
	request_authorization_token_1_arg.refresh = calloc(2, sizeof(char));

	for (int i = 0; i < size_orders; i++) {
		
		if (strcmp(orders[i].action, "REQUEST") == 0) {
			strcpy(request_authorization_token_1_arg.id, orders[i].id);
			strcpy(request_authorization_token_1_arg.refresh, orders[i].details);
			result_1 = request_authorization_token_1(&request_authorization_token_1_arg, clnt);
			break;
		}
	}
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("%s\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *path;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	path = argv[2];
	grade_prog_1 (host, path);
exit (0);
}
