/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "OAuth.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include "OAuth_utils.h"

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
grade_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		authorization request_authorization_token_1_arg;
		approve approve_request_token_1_arg;
		access request_access_token_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case request_authorization_token:
		_xdr_argument = (xdrproc_t) xdr_authorization;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) request_authorization_token_1_svc;
		break;

	case approve_request_token:
		_xdr_argument = (xdrproc_t) xdr_approve;
		_xdr_result = (xdrproc_t) xdr_approve_response;
		local = (char *(*)(char *, struct svc_req *)) approve_request_token_1_svc;
		break;

	case request_access_token:
		_xdr_argument = (xdrproc_t) xdr_access;
		_xdr_result = (xdrproc_t) xdr_access_response;
		local = (char *(*)(char *, struct svc_req *)) request_access_token_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
grade_prog_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		action validate_delegated_action_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case validate_delegated_action:
		_xdr_argument = (xdrproc_t) xdr_action;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) validate_delegated_action_2_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
grade_prog_3(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		refresh_input get_new_token_3_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case get_new_token:
		_xdr_argument = (xdrproc_t) xdr_refresh_input;
		_xdr_result = (xdrproc_t) xdr_refresh_output;
		local = (char *(*)(char *, struct svc_req *)) get_new_token_3_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	char *clients_path = argv[1];
	char *resources_path = argv[2];
	char *approvals_path = argv[3];
	valability = atoi(argv[4]);

	get_clients(clients_path);
	get_resources(resources_path);
	read_permissions(approvals_path);
	
	register SVCXPRT *transp;

	pmap_unset (GRADE_PROG, GRADE_VERS);
	pmap_unset (GRADE_PROG, GRADE_VERS_2);
	pmap_unset (GRADE_PROG, GRADE_VERS_3);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, GRADE_PROG, GRADE_VERS, grade_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (GRADE_PROG, GRADE_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, GRADE_PROG, GRADE_VERS_2, grade_prog_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (GRADE_PROG, GRADE_VERS_2, udp).");
		exit(1);
	}
	if (!svc_register(transp, GRADE_PROG, GRADE_VERS_3, grade_prog_3, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (GRADE_PROG, GRADE_VERS_3, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, GRADE_PROG, GRADE_VERS, grade_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (GRADE_PROG, GRADE_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, GRADE_PROG, GRADE_VERS_2, grade_prog_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (GRADE_PROG, GRADE_VERS_2, tcp).");
		exit(1);
	}
	if (!svc_register(transp, GRADE_PROG, GRADE_VERS_3, grade_prog_3, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (GRADE_PROG, GRADE_VERS_3, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
