/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "OAuth.h"
#include "OAuth_utils.h"
#include "token.h"

char **
request_authorization_token_1_svc(authorization *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	for (int i = 0; i < clients->size; i++) {
		if (strcmp(argp->id, clients->clients[i]) == 0) {
			strcpy(result, generate_access_token(argp->id));
			break;
		}
	}
	return &result;
}
