/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "OAuth.h"
#include "OAuth_utils.h"

void
grade_prog_1(char *host, char *id, char *refresh)
{
	CLIENT *clnt;
	char * *result_1;
	authorization  request_authorization_token_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, GRADE_PROG, GRADE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	request_authorization_token_1_arg.id = calloc(16, sizeof(char));
	request_authorization_token_1_arg.refresh = calloc(2, sizeof(char));

	strcpy(request_authorization_token_1_arg.id, id);
	strcpy(request_authorization_token_1_arg.refresh, refresh);

	result_1 = request_authorization_token_1(&request_authorization_token_1_arg, clnt);

	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("%s\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *path;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	path = argv[2];

	int size_orders = 0;
	ClientOrder* orders = get_orders(path, &size_orders);

	for (int i = 0; i< size_orders; i++) {
		char *id = orders[i].id;
		char *action = orders[i].action;
		char *details = orders[i].details;

		if (strcmp(action, "REQUEST") == 0) {
			grade_prog_1(host, id, details);
		}
	}

	exit (0);
}
